experiment_name: "LSTM_Baseline_01"


LSTM:
  hyperparameters:
    input_size: 1
    hidden_size: 64
    num_layers: 2
    dropout: 0.1
    output_size: 1
    
  training:
    batch_size: 32
    learning_rate: 0.001
    epochs: 300
    device: "auto"



Paths:
  data_dir: "../data/tensors_qv"
  save_dir: "../models"


